### ISSUE TITLE
Getting errors when I ran the project

### ISSUE THREAD

**Issue by nuweb** [ModusCreateOrg/react-dynamic-route-loading-es6#10]
Hi, I would like to help with server-rendering, but getting following errors when running the project.

```
ERROR in ./general.scss
Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/general.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @charset "UTF-8";
| @import "./variables";
|

ERROR in ./components/List/list.scss
Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/List/list.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "client/variables";
|
| .list {

ERROR in ./components/Header/header.scss
Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/Header/header.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "client/variables";
|
| .header-container {

ERROR in ./containers/App/style.scss
Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/containers/App/style.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .viewport {
|     margin-top:2.4em;
| }

ERROR in ./components/Toolbar/toolbar.scss
Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/Toolbar/toolbar.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "client/variables";
|
| .navbar {

ERROR in ./components/Toolbar/toolbar.scss
Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/Toolbar/toolbar.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "client/variables";
|
| .navbar {

ERROR in ./components/Toolbar/toolbar.scss
Module build failed: ModuleParseError: Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/Toolbar/toolbar.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "client/variables";
|
| .navbar {
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:207:34
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:164:10
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.provide (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:53:20)
    at CachedInputFileSystem.readFile (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:160:24)
    at processResource (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:194:11)
    at iteratePitchingLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:153:10)
    at runLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:131:2)
    at NormalModule.build (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:179:15)
    at Compilation.buildModule (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/Compilation.js:127:9)
    at Compilation.<anonymous> (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/Compilation.js:404:8)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:74:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/tapable/lib/Tapable.js:123:70)
    at onDoneResolving (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:49:11)
    at onDoneResolving (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:165:6)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:161:6
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3694:9
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:936:13)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:840:16
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3691:13
    at apply (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:21:25)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:56:12
    at NormalModuleFactory.resolveRequestArray (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:213:32)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3686:9
    at eachOfArrayLike (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:941:9)
    at eachOf (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:991:5)
    at _parallel (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3685:5)

ERROR in /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/Toolbar/toolbar.scss doesn't export content

ERROR in ./containers/App/style.scss
Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/containers/App/style.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .viewport {
|     margin-top:2.4em;
| }

ERROR in ./containers/App/style.scss
Module build failed: ModuleParseError: Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/containers/App/style.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .viewport {
|     margin-top:2.4em;
| }
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:207:34
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:164:10
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.provide (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:53:20)
    at CachedInputFileSystem.readFile (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:160:24)
    at processResource (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:194:11)
    at iteratePitchingLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:153:10)
    at runLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:131:2)
    at NormalModule.build (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:179:15)
    at Compilation.buildModule (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/Compilation.js:127:9)
    at Compilation.<anonymous> (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/Compilation.js:404:8)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:74:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/tapable/lib/Tapable.js:123:70)
    at onDoneResolving (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:49:11)
    at onDoneResolving (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:165:6)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:161:6
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3694:9
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:936:13)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:840:16
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3691:13
    at apply (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:21:25)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:56:12
    at NormalModuleFactory.resolveRequestArray (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:213:32)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3686:9
    at eachOfArrayLike (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:941:9)
    at eachOf (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:991:5)
    at _parallel (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3685:5)

ERROR in /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/containers/App/style.scss doesn't export content

ERROR in ./general.scss
Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/general.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @charset "UTF-8";
| @import "./variables";
|

ERROR in ./general.scss
Module build failed: ModuleParseError: Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/general.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @charset "UTF-8";
| @import "./variables";
|
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:207:34
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:164:10
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.provide (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:53:20)
    at CachedInputFileSystem.readFile (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:160:24)
    at processResource (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:194:11)
    at iteratePitchingLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:153:10)
    at runLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:131:2)
    at NormalModule.build (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:179:15)
    at Compilation.buildModule (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/Compilation.js:127:9)
    at Compilation.<anonymous> (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/Compilation.js:404:8)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:74:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/tapable/lib/Tapable.js:123:70)
    at onDoneResolving (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:49:11)
    at onDoneResolving (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:165:6)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:161:6
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3694:9
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:936:13)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:840:16
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3691:13
    at apply (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:21:25)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:56:12
    at NormalModuleFactory.resolveRequestArray (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:213:32)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3686:9
    at eachOfArrayLike (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:941:9)
    at eachOf (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:991:5)
    at _parallel (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3685:5)

ERROR in /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/general.scss doesn't export content

ERROR in ./components/Header/header.scss
Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/Header/header.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "client/variables";
|
| .header-container {

ERROR in ./components/Header/header.scss
Module build failed: ModuleParseError: Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/Header/header.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "client/variables";
|
| .header-container {
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:207:34
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:164:10
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.provide (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:53:20)
    at CachedInputFileSystem.readFile (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:160:24)
    at processResource (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:194:11)
    at iteratePitchingLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:153:10)
    at runLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:131:2)
    at NormalModule.build (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:179:15)
    at Compilation.buildModule (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/Compilation.js:127:9)
    at Compilation.<anonymous> (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/Compilation.js:404:8)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:74:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/tapable/lib/Tapable.js:123:70)
    at onDoneResolving (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:49:11)
    at onDoneResolving (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:165:6)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:161:6
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3694:9
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:936:13)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:840:16
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3691:13
    at apply (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:21:25)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:56:12
    at NormalModuleFactory.resolveRequestArray (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:213:32)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3686:9
    at eachOfArrayLike (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:941:9)
    at eachOf (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:991:5)
    at _parallel (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3685:5)

ERROR in /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/Header/header.scss doesn't export content

ERROR in ./components/List/list.scss
Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/List/list.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "client/variables";
|
| .list {

ERROR in ./components/List/list.scss
Module build failed: ModuleParseError: Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/List/list.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "client/variables";
|
| .list {
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:207:34
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:164:10
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.provide (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:53:20)
    at CachedInputFileSystem.readFile (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:160:24)
    at processResource (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:194:11)
    at iteratePitchingLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:153:10)
    at runLoaders (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:131:2)
    at NormalModule.build (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModule.js:179:15)
    at Compilation.buildModule (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/Compilation.js:127:9)
    at Compilation.<anonymous> (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/Compilation.js:404:8)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:74:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/tapable/lib/Tapable.js:123:70)
    at onDoneResolving (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:49:11)
    at onDoneResolving (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:165:6)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:161:6
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3694:9
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:936:13)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:840:16
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3691:13
    at apply (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:21:25)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:56:12
    at NormalModuleFactory.resolveRequestArray (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/lib/NormalModuleFactory.js:213:32)
    at /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3686:9
    at eachOfArrayLike (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:941:9)
    at eachOf (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:991:5)
    at _parallel (/Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/webpack/node_modules/async/dist/async.js:3685:5)

ERROR in /Users/csekharveera/Sites/react-dynamic-route-loading-es6/node_modules/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!style-loader!css-loader!sass-loader!/Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/List/list.scss doesn't export content
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./components/Toolbar/toolbar.scss
    Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/Toolbar/toolbar.scss Unexpected character '@' (1:0)
    You may need an appropriate loader to handle this file type.
    | @import "client/variables";
    |
    | .navbar {
Child extract-text-webpack-plugin:
       [0] ./containers/App/style.scss 261 bytes {0} [built] [failed] [1 error]

    ERROR in ./containers/App/style.scss
    Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/containers/App/style.scss Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    | .viewport {
    |     margin-top:2.4em;
    | }
Child extract-text-webpack-plugin:
       [0] ./general.scss 266 bytes {0} [built] [failed] [1 error]

    ERROR in ./general.scss
    Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/general.scss Unexpected character '@' (1:0)
    You may need an appropriate loader to handle this file type.
    | @charset "UTF-8";
    | @import "./variables";
    |
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./components/Header/header.scss
    Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/Header/header.scss Unexpected character '@' (1:0)
    You may need an appropriate loader to handle this file type.
    | @import "client/variables";
    |
    | .header-container {
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./components/List/list.scss
    Module parse failed: /Users/csekharveera/Sites/react-dynamic-route-loading-es6/client/components/List/list.scss Unexpected character '@' (1:0)
    You may need an appropriate loader to handle this file type.
    | @import "client/variables";
    |
    | .list {

```

**Comment by veeracs** [comment]
Please close this, I finally got this working after making some updates to webpack config and updating webpack versions.

**Comment by erdillon** [comment]
@veeracs getting the same errors. Could you share what you did to get it to work?

**Comment by ajmajma** [comment]
Bump , what did you do to fix this please?

**Comment by veeracs** [comment]
Here's the repo,
https://github.com/veeracs/react-universal-kickstarter/blob/master/webpack.config.js

**Comment by grgur** [comment]
Please check out the code again and re-install dependencies with `npm i` or `yarn`. Working with the latest Webpack, too
